# Generated by Django 4.2.2 on 2023-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatures',
            name='image',
            field=models.ImageField(default='', upload_to='app/images'),
        ),
        migrations.AddField(
            model_name='creatures',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
