# Generated by Django 4.2.2 on 2023-06-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_alter_creatures_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatures',
            name='type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
