# Generated by Django 4.2.2 on 2023-06-28 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_creatures_type_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='creatures',
            name='type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
