# Generated by Django 4.2.2 on 2023-07-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addplayers_points_teams_upcoming_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_logo', models.ImageField(default='', upload_to='game/images')),
                ('team_homevenue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='register_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_type', models.CharField(max_length=100)),
                ('player_age', models.IntegerField(default=18)),
                ('player_image', models.ImageField(default='', upload_to='shopp/images')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registerteam')),
            ],
        ),
    ]
