# Generated by Django 4.2.2 on 2023-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_previous_match_unique_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcart',
            name='match_unique_namee',
        ),
        migrations.AddField(
            model_name='ticketcart',
            name='match_unique_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
