# Generated by Django 4.2.2 on 2023-07-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_teams_teams_trophies_teams_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addplayers',
            name='team',
            field=models.CharField(default='', max_length=60),
        ),
    ]
