# Generated by Django 4.2.2 on 2023-08-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_profile_age_profile_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
