# Generated by Django 4.2.2 on 2023-07-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_description', models.TextField(default='')),
                ('product_image', models.ImageField(default='', upload_to='shopp/images')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harryshop.category')),
            ],
        ),
    ]
