# Generated by Django 4.2.2 on 2023-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harryshop', '0004_category_remove_product_category_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
