# Generated by Django 4.2.2 on 2023-07-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harryshop', '0006_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
