# Generated by Django 4.2.2 on 2023-07-27 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harryshop', '0008_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='registermatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('match_venue', models.CharField(max_length=100)),
                ('match_time', models.TimeField()),
                ('match_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='registered_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_category', models.CharField(max_length=100)),
                ('player_age', models.IntegerField(default=18)),
                ('player_image', models.ImageField(default='', upload_to='shopp/images')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harryshop.registermatch')),
            ],
        ),
    ]
