# Generated by Django 4.2.2 on 2023-07-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harryshop', '0009_registermatch_registered_players'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered_players',
        ),
        migrations.DeleteModel(
            name='registermatch',
        ),
    ]
